package com.andreas.domain;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Represents a user entity within the Kafka playground ecosystem.
 * This record is used for cross-platform data exchange between the
 * TypeScript producer and the Java consumer.
 *
 * @param id          Unique identifier generated by the producer.
 * @param firstName   The user's first name.
 * @param lastName    The user's last name.
 * @param birthDate   Date of birth, used for age calculation strategies.
 * @param trustLevel  A value between 0-10 defining the reliability of the user.
 * @param lastSeen    Timestamp of the last recorded activity.
 */
public record User (
    UUID id,
    String firstName,
    String lastName,
    LocalDate birthDate,
    int trustLevel,
    Instant lastSeen
){}